### ISSUE TITLE
IgnoreQueryFilters does not work when using Set<> method in DbContext

### ISSUE THREAD

**Issue by kasahara-t** [remihenache/ThreadSafeDbContext#3]
Hi,

First of all, thank you for your excellent implementation of `ThreadSafeDbContext`. It has been incredibly helpful in my current project.

While testing the behavior of `IgnoreQueryFilters`, I encountered an inconsistency when using it with `DbSet<>` properties versus the `Set<>` method in DbContext:

* `IgnoreQueryFilters` works as expected when applied to `DbSet<>` properties in my DbContext.

* However, when retrieving a DbSet via `DbContext.Set<>()` and applying `IgnoreQueryFilters`, it does not behave correctly, and the query filters are not ignored.
I have created a sample repository to demonstrate this issue. You can find it here:
https://github.com/kasahara-t/thread-safe-dbcontext-rls

I would greatly appreciate it if you could investigate this behavior or provide any guidance on how to resolve the issue. If there's anything else you'd like me to clarify or modify in the sample repository, please let me know.

**Comment by remihenache** [comment]
Thanks for this content.
I'll try to find the issue and bring a solution.

**Comment by remihenache** [comment]
I just created a new branch to fix the issue.
I also created a DbWrapper, to allow you to use it, still using the IdentityDbContext you have to use.
`var myDbContextToUse = ThreadSafeDbContext.Wrap<IdentityDbContext>(dbContext);`
I created a preview package nugget if you need, otherwise, you can check the branch https://github.com/remihenache/ThreadSafeDbContext/tree/fix/Queryfilters-issues

It seems like there can be some issues using the wrapper (whereas the ThreadsafeDbContext works great), but all tests are green. Tell me if you meet some problems.

Don't forget that if you want to declare DbSet on your context, you have to do something like this:
`
public class TestDbContext : ThreadSafeDbContext
{
    public DbSet<SampleEntity> SampleEntities => this.Set<SampleEntity>()
}
`
Except what I'm not sur the DbSet will be threadsafe

**Comment by kasahara-t** [comment]
First of all, I want to express my deepest gratitude for your prompt response and the amazing work you’ve done to address the issue. The fix in the branch works perfectly, and I am truly impressed with how quickly you resolved the problem!

Regarding the `DbWrapper` you kindly created, I won’t be using it. The reason is that my goal is to create a class that directly inherits from `IdentityDbContext`, which doesn't align with wrapping the context.

I completely understand that, in order to use `ThreadSafeDbSet`, the properties would need to go through the `Set<>` method, and I’m fully aware that it’s not entirely thread-safe. However, I’ve come to realize that the root cause of my issue lies in the framework combination I’m using, which will likely require a more fundamental design review to resolve properly.

That said, I cannot emphasize enough how much your assistance has meant to me. Your insights and the changes you’ve made have been incredibly valuable, and I’m sincerely thankful for your help in guiding me through this challenge.

Once again, thank you for everything, and I look forward to seeing more of your great work in the future!

**Comment by remihenache** [comment]
Thanks for your incredible answer !
I'll not recomend anyone to use this library, except if there is no other choices. Ideally, you should have on DbContext instance per thread, so you'll don't have any issue.
This library is made for edge case, like multithreading transaction share, or some lazyloading optimization.
So if you can rethink your design, I can only encouraged you to do that !
And if you can't, you can still use this library :)
